export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (id: string) => `/products/${id}`,
  PRODUCT_NEW: '/products/new',
  OPERATIONS: '/operations',
  RECEIPTS: '/operations/receipts',
  DELIVERIES: '/operations/deliveries',
  TRANSFERS: '/operations/transfers',
  ADJUSTMENTS: '/operations/adjustments',
  OPERATION_DETAIL: (id: string) => `/operations/${id}`,
  OPERATION_NEW: '/operations/new',
  MOVE_HISTORY: '/move-history',
  WAREHOUSES: '/warehouses',
  SETTINGS: '/settings',
  PROFILE: '/profile',
};
