import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env";
import { errorHandler } from "./middleware/errorHandler";
import authRoutes from "./routes/auth.routes";
import operationRoutes from "./routes/operation.routes";
import stockRoutes from "./routes/stock.routes";

const app = express();
app.use(helmet());
app.use(cors({ origin: "http://localhost:3000", credentials: true }));
app.use(morgan("dev"));
app.use(express.json({ limit: "10mb" }));
app.get("/api/v1/health", (req, res) => res.json({ status: "ok", timestamp: new Date().toISOString(), service: "StockSense API" }));
app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/operations", operationRoutes);
app.use("/api/v1/stock", stockRoutes);
app.use(errorHandler);
app.listen(env.PORT, () => console.log(`StockSense API running on http://localhost:${env.PORT}`));
export default app;
